### ISSUE TITLE
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://objectstorage.us-phoenix-1.oraclecloud.com/n/dwcsdev/b/adb-free/o/ADBS-23.10.2.4/MY_%22ATP%22.pdb

### ISSUE THREAD

**Issue by alexesca** [oracle/adb-free#16]
I am trying to run the container with docker compose, but get the following. I thought it was ma laptop, but got the same error from a different computer. See docker compose and errors below

```yml
version: "3"
services:
  adb-free:
    container_name: adb-free
    image: container-registry.oracle.com/database/adb-free:latest
    hostname: localhost
    ports:
      - "1521:1522"
      - "1522:1522"
      - "8443:8443"
      - "27017:27017"
    environment:
      - WORKLOAD_TYPE="ATP"
      - WALLET_PASSWORD=${WALLET_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse"

**Comment by alexesca** [comment]
```json
{
"code": "ObjectNotFound",
"message": "The object 'ADBS-23.10.2.4/MY_\"ATP\".pdb' was not found in the bucket 'adb-free'"
}

**Comment by alexesca** [comment]
```ts
adb-free  | updating: cwallet.sso (stored 0%)
adb-free  | updating: cwallet.sso.lck (stored 0%)
adb-free  | updating: ewallet.p12 (stored 0%)
adb-free  | updating: ewallet.p12.lck (stored 0%)
adb-free  | updating: ewallet.pem (deflated 25%)
adb-free  | updating: keystore.jks (stored 0%)
adb-free  | updating: ojdbc.properties (deflated 49%)
adb-free  | updating: sqlnet.ora (deflated 16%)
adb-free  | updating: tnsnames.ora (stored 0%)
adb-free  | updating: truststore.jks (deflated 5%)
adb-free  | TIME ELAPSED Wallet Generation: 0 minutes and 11 seconds elapsed
adb-free  | User has requested to download '.pdb' archive file from Object Storage bucket
adb-free  | Downloading MY_"ATP".pdb..
adb-free  | Traceback (most recent call last):
adb-free  |   File "/u01/scripts/download_my_container_pdb.py", line 89, in <module>
adb-free  |     downloader.download()
adb-free  |   File "/u01/scripts/download_my_container_pdb.py", line 57, in download
adb-free  |     r.raise_for_status()
adb-free  |   File "/usr/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
adb-free  |     raise HTTPError(http_error_msg, response=self)
adb-free  | requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://objectstorage.us-phoenix-1.oraclecloud.com/n/dwcsdev/b/adb-free/o/ADBS-23.10.2.4/MY_%22ATP%22.pdb
adb-free exited with code 1

**Comment by alexesca** [comment]
I found the issue. It was complaining about how I declared my ATP type

```yml
    environment:
      - WORKLOAD_TYPE="ATP"

I needed to do 

```yml
    environment:
      - WORKLOAD_TYPE=ATP
