### ISSUE TITLE
Input JSON not found

### ISSUE THREAD

**Issue by ACCBMW** [oracle/adb-free#18]
I had installed Oracle 19C on docker
Run this command --> docker run -d -p 1521:1522 -p 1522:1522 -p 8443:8443 -p 27017:27017 -e WORKLOAD_TYPE='ATP' -e WALLET_PASSWORD=pass123 -e ADMIN_PASSWORD=pass123 --cap-add SYS_ADMIN --device /dev/fuse --name adb-free ghcr.io/oracle/adb-free:latest

Container starts but after few mins. it gives below error 

Also Run this command but nothing happens, command --> docker exec adb-free adb-cli add-database --workload-type "ADW" --admin-password "Welcome_1234"

2024-04-18 11:53:14 Archive:  /u01/POD1.zip
2024-04-18 11:53:14    creating: /u01/app/oracle/oradata/
2024-04-18 11:53:14    creating: /u01/app/oracle/oradata/POD1/
2024-04-18 11:53:14    creating: /u01/app/oracle/oradata/POD1/1448BDF51BE70DD7E063853946645191/
2024-04-18 11:53:14    creating: /u01/app/oracle/oradata/POD1/1448BDF51BE70DD7E063853946645191/datafile/
2024-04-18 11:53:14   inflating: /u01/app/oracle/oradata/POD1/1448BDF51BE70DD7E063853946645191/datafile/o1_mf_temp_m01dvz70_.tmp  
2024-04-18 11:53:15   inflating: /u01/app/oracle/oradata/POD1/redo01.log  
2024-04-18 11:53:15    creating: /u01/app/oracle/oradata/POD1/14716035B722431CE0636402000A9BD7/
2024-04-18 11:53:15    creating: /u01/app/oracle/oradata/POD1/14716035B722431CE0636402000A9BD7/datafile/
2024-04-18 11:53:15   inflating: /u01/app/oracle/oradata/POD1/redo02.log  
2024-04-18 11:53:15    creating: /u01/app/oracle/oradata/POD1/147167519AA8472EE0636402000A7798/
2024-04-18 11:53:15    creating: /u01/app/oracle/oradata/POD1/147167519AA8472EE0636402000A7798/datafile/
2024-04-18 11:53:15    creating: /u01/app/oracle/oradata/POD1/datafile/
2024-04-18 11:53:15   inflating: /u01/app/oracle/oradata/POD1/datafile/o1_mf_undotbs1_m01fswxh_.dbf  
2024-04-18 11:53:15   inflating: /u01/app/oracle/oradata/POD1/datafile/o1_mf_temp_m01dvy2l_.tmp  
2024-04-18 11:54:47   inflating: /u01/app/oracle/oradata/POD1/datafile/o1_mf_system_m01dogtm_.dbf  
2024-04-18 11:55:47   inflating: /u01/app/oracle/oradata/POD1/datafile/o1_mf_sysaux_m01dogv2_.dbf  
2024-04-18 11:55:47   inflating: /u01/app/oracle/oradata/POD1/datafile/o1_mf_temp_m01fsxpg_.tmp  
2024-04-18 11:55:51   inflating: /u01/app/oracle/oradata/POD1/datafile/o1_mf_data_m01dogvl_.dbf  
2024-04-18 11:55:51    creating: /u01/app/oracle/oradata/POD1/onlinelog/
2024-04-18 11:55:51    creating: /u01/app/oracle/oradata/POD1/1471656206A546B4E0636402000ACA7D/
2024-04-18 11:55:51    creating: /u01/app/oracle/oradata/POD1/1471656206A546B4E0636402000ACA7D/datafile/
2024-04-18 11:55:51    creating: /u01/app/oracle/oradata/POD1/1449FAC698DB3341E0638539466443E4/
2024-04-18 11:55:51    creating: /u01/app/oracle/oradata/POD1/1449FAC698DB3341E0638539466443E4/datafile/
2024-04-18 11:55:51   inflating: /u01/app/oracle/oradata/POD1/1449FAC698DB3341E0638539466443E4/datafile/o1_mf_temp_m01dw17o_.tmp  
2024-04-18 11:55:51    creating: /u01/app/oracle/oradata/POD1/controlfile/
2024-04-18 11:55:52   inflating: /u01/app/oracle/oradata/POD1/controlfile/o1_mf_m01dy2hr_.ctl  
2024-04-18 11:55:52 TIME ELAPSED Unzipping /u01/POD1.zip: 2 minutes and 38 seconds elapsed
2024-04-18 11:55:52 User input JSON not found
2024-04-18 11:55:52 Traceback (most recent call last):
2024-04-18 11:55:52   File "/u01/scripts/user_input.py", line 91, in <module>
2024-04-18 11:55:52     generate_default_input_json()
2024-04-18 11:55:52   File "/u01/scripts/user_input.py", line 67, in generate_default_input_json
2024-04-18 11:55:52     raise ValueError(f"{database_name} is not alphanumeric")
2024-04-18 11:55:52 ValueError: MY'ATP' is not alphanumeric

**Comment by aosingh** [comment]
@ACCBMW 

The error is -> `MY'ATP' is not alphanumeric`

Try the container start command without single quotes in WORKLOAD_TYPE

```bash
docker run -d \
-p 1521:1522 \
-p 1522:1522 \
-p 8443:8443 \
-p 27017:27017 \
-e WORKLOAD_TYPE=ATP \
-e WALLET_PASSWORD=pass123 \
-e ADMIN_PASSWORD=pass123 \
--cap-add SYS_ADMIN \
--device /dev/fuse \
--name adb-free \
ghcr.io/oracle/adb-free:latest
```
Also, the password pass123 does not meet complexity requirements. You might have to increase the length to alteast 8 characters and also include an uppercase character

**Comment by ACCBMW** [comment]
Thanks Its working now,
